services:
  - type: web
    name: checkit-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_BASE
        sync: false
